#!/bin/sh

echo "Running daily Certbot renewal check"
exec /usr/bin/certbot renew --verbose --non-interactive --cert-name bookstack \
    --nginx --nginx-server-root /config/nginx \
	--user-agent-comment 'bookstack-certbot'

